@baseUrl = http://localhost:3000


# Users

### @name FindAll-Users
GET {{baseUrl}}/user

### @name Find-User
GET {{baseUrl}}/user/1

### @name Create-User
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "Lucas Berriel",
    "email": "lucas@teste.com",
    "password": "123456",
    "role": "admin"
}

### @name Update-User
PATCH   {{baseUrl}}/user/10
Content-Type: application/json

{
    "role": "admin"
}

### @name Remove-User
DELETE {{baseUrl}}/user/3






# Itens

### @name FindAll-Items
GET {{baseUrl}}/items

### @name Find-Item
GET {{baseUrl}}/items/25

### @name Create-Item
POST {{baseUrl}}/items
Content-Type: application/json

{
    "name": "Produto 01",
    "unit": "unit",
    "description": "Exemplo",
    "item_type": "product",
    "raw_materials": [
        {
            "raw_material_id": 23,
            "quantity": 45
        },
        {
            "raw_material_id": 22,
            "quantity": 23
        }
    ]
    
}


### @name Update-Item
PATCH   {{baseUrl}}/items/989
Content-Type: application/json

{
    "raw_materials": [
        {
            "raw_material_id": 23,
            "quantity": 10
        }
    ]
}

### @name Update-Inventory-Item
PATCH   {{baseUrl}}/items/12/inventory
Content-Type: application/json

{
    "quantity": 1000
}

### @name Remove-Item
DELETE {{baseUrl}}/items/26







# Máquina

### @name FindAll-Machines
GET {{baseUrl}}/machines

### @name Find-Machine
GET {{baseUrl}}/machines/2

### @name Create-Machine
POST {{baseUrl}}/machines
Content-Type: application/json

{
    "name": "Polideira"
}

### @name Update-Machine
PATCH   {{baseUrl}}/machines/1
Content-Type: application/json

{
    "name": "Lichadeira"
}

### @name Remove-Machine
DELETE {{baseUrl}}/machines/1
