@baseUrl = http://localhost:3000


# Users

### @name FindAll-Users
GET {{baseUrl}}/users

### @name Find-User
GET {{baseUrl}}/user/1

### @name Create-User
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Mayara",
    "email": "mayara@teste.com",
    "role": "admin"
}

### @name Update-User
PATCH   {{baseUrl}}/user/10
Content-Type: application/json

{
    "role": "admin"
}

### @name Remove-User
DELETE {{baseUrl}}/user/3






# Itens

### @name FindAll-Items
GET {{baseUrl}}/items

### @name Find-Item
GET {{baseUrl}}/items/7

### @name Create-Item
POST {{baseUrl}}/items
Content-Type: application/json

{
    "name": "Produto 02",
    "unit": "unit",
    "description": "Exemplo",
    "item_type": "product",
    "quantity": 10,
    "raw_materials": [
        {
            "raw_material_id": 5,
            "quantity": 45
        }
    ]
}


### @name Update-Item
PATCH   {{baseUrl}}/items/7
Content-Type: application/json

{
    "raw_materials": [
        {
            "raw_material_id": 3,
            "quantity": 18
        }
    ]
}

### @name Update-Inventory-Item
PATCH   {{baseUrl}}/items/12/inventory
Content-Type: application/json

{
    "quantity": 1000
}

### @name Remove-Item
DELETE {{baseUrl}}/items/26







# Máquina

### @name FindAll-Machines
GET {{baseUrl}}/machines

### @name Find-Machine
GET {{baseUrl}}/machines/2

### @name Create-Machine
POST {{baseUrl}}/machines
Content-Type: application/json

{
    "name": "Polideira"
}

### @name Update-Machine
PATCH   {{baseUrl}}/machines/1
Content-Type: application/json

{
    "name": "Lichadeira"
}

### @name Remove-Machine
DELETE {{baseUrl}}/machines/1
